------------------------------------------------------------
----------------  . C I I    T O   . N T L  ----------------
------------  E R R O R S   A N D   W A R N I N G S --------
------------------------------------------------------------

 *** WARNING ***
 Support type is not available                                                  
 Support ignored @ Node 35                                                      
 *** WARNING ***
 Support type is not available                                                  
 Support ignored @ Node 37                                                      
 
********* AUTOPIPE BATCH NTL FILE: QA327F.NTL
 
********* NUMBER OF ERRORS   =    0
********* NUMBER OF WARNINGS =    2




          * * * *  APIN MESSAGE FILE  * * * * 


*** LAST NODE PROCESSED: 1    
OPER          1       260.0000      2068.4299                                   
          *** WARNING: INVALID LONG. WELD TYPE. SEAMLESS ASSUMED.
*** LAST NODE PROCESSED: 5    
RUN  7                 127.000     0.000     0.000                              
          *** WARNING: INVALID LONG. WELD TYPE. SEAMLESS ASSUMED.
*** LAST NODE PROCESSED: 7    
OPER          2        70.0000      1378.9500                                   
          *** WARNING: INVALID LONG. WELD TYPE. SEAMLESS ASSUMED.
*** LAST NODE PROCESSED: 9   F
RUN  15                  0.000   -50.800     0.000                              
          *** WARNING: INVALID LONG. WELD TYPE. SEAMLESS ASSUMED.
*** LAST NODE PROCESSED: 25   
RUN  27                  0.000     0.000    76.200                              
          *** WARNING: INVALID LONG. WELD TYPE. SEAMLESS ASSUMED.
*** LAST NODE PROCESSED: 41   
INCL 21           W .21015E+04   76.2000   76.2000   76.2000   76.2000    0.4000
          *** NOTE: SUPPORT NAMES GENERATED BY TRANSLATOR


      DATABASE ARRAY SIZE IS  18150.  MAXIMUM ALLOWABLE IS   10000000



 ********** NUMBER OF ERRORS:   0
 ********** NUMBER OF WARNINGS:   5


