          * * * *  APIN MESSAGE FILE  * * * * 


*** LAST NODE PROCESSED: A01  
FLA  A01  WELDNECK    16 WN       24.30               0.000                     
          *** WARNING: UNRECOGNIZED RATING. FLANGE IS NON-STANDARD.
*** LAST NODE PROCESSED: A10  
FLA  A10  WELDNECK    16 WN       24.30               0.000                     
          *** WARNING: UNRECOGNIZED RATING. FLANGE IS NON-STANDARD.


      DATABASE ARRAY SIZE IS  23424.  MAXIMUM ALLOWABLE IS   10000000



 ********** NUMBER OF ERRORS:   0
 ********** NUMBER OF WARNINGS:   2


