------------------------------------------------------------
----------------  . C I I    T O   . N T L  ----------------
------------  E R R O R S   A N D   W A R N I N G S --------
------------------------------------------------------------

 
********* AUTOPIPE BATCH NTL FILE: QA333C_0.NTL
 
********* NUMBER OF ERRORS   =    0
********* NUMBER OF WARNINGS =    0




          * * * *  APIN MESSAGE FILE  * * * * 


*** LAST NODE PROCESSED: 30   
RED  30                  0.000   609.600     0.000     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.
*** LAST NODE PROCESSED: 50   
RED  50                -76.200   911.352     0.000     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.
*** LAST NODE PROCESSED: 90   
RED  90                  0.000   280.415   707.136     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.
*** LAST NODE PROCESSED: 110  
RED  110                 0.000   280.416   707.136     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.


      DATABASE ARRAY SIZE IS  18687.  MAXIMUM ALLOWABLE IS   10000000



 ********** NUMBER OF ERRORS:   0
 ********** NUMBER OF WARNINGS:   4


