------------------------------------------------------------
----------------  . C I I    T O   . N T L  ----------------
------------  E R R O R S   A N D   W A R N I N G S --------
------------------------------------------------------------

 
********* AUTOPIPE BATCH NTL FILE: QA333B_0.NTL
 
********* NUMBER OF ERRORS   =    0
********* NUMBER OF WARNINGS =    0




          * * * *  APIN MESSAGE FILE  * * * * 


*** LAST NODE PROCESSED: 10   
PIPE PIPE1             60.3242    3.9116    0.2540                              
          *** ERROR: NO INSIDE DIA. GIVEN. PIPE IGNORED.
*** LAST NODE PROCESSED: 10   
    *NS                   0.062.10921001        .0  8009.230     0.3002.10921001
          *** ERROR: UNSUPPORTED OR UNRECOGNIZED ELEMENT TAG.
*** LAST NODE PROCESSED: 10   
    *                   6.3500  256.2950    1.0000                              
          *** ERROR: UNSUPPORTED OR UNRECOGNIZED ELEMENT TAG.
*** LAST NODE PROCESSED: 10   
    *                   1.0000                  .0                              
          *** ERROR: UNSUPPORTED OR UNRECOGNIZED ELEMENT TAG.
*** LAST NODE PROCESSED: 45   
RED  45                 50.779   609.347     0.000     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.
*** LAST NODE PROCESSED: 45   
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 125  
RED  125                 0.000   280.416   707.136     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.
*** LAST NODE PROCESSED: 125  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 125  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 230  
FLA  230  WELDNECK  2500 BW       21.319                                        
          *** WARNING: UNRECOGNIZED RATING. FLANGE IS NON-STANDARD.
*** LAST NODE PROCESSED: 250  
FLA  250  WELDNECK  2500 BW       20.866                                        
          *** WARNING: UNRECOGNIZED RATING. FLANGE IS NON-STANDARD.
*** LAST NODE PROCESSED: 280  
FLA  280  WELDNECK  2500 BW        4.536                                        
          *** WARNING: UNRECOGNIZED RATING. FLANGE IS NON-STANDARD.
*** LAST NODE PROCESSED: 330  
FLA  330  WELDNECK  2500 BW       32.659                                        
          *** WARNING: UNRECOGNIZED RATING. FLANGE IS NON-STANDARD.
*** LAST NODE PROCESSED: 380 N
FLA  380 N        NS   NS                                                       
          *** WARNING: UNRECOGNIZED WELD TYPE. BUTT-WELD ASSUMED.
*** LAST NODE PROCESSED: 420  
FLA  420  WELDNECK  2500 BW        4.536                                        
          *** WARNING: UNRECOGNIZED RATING. FLANGE IS NON-STANDARD.
*** LAST NODE PROCESSED: 440  
FLA  440  WELDNECK  2500 BW      283.500                                        
          *** WARNING: UNRECOGNIZED RATING. FLANGE IS NON-STANDARD.
*** LAST NODE PROCESSED: 460 N
FLA  460 N        NS   NS                                                       
          *** WARNING: UNRECOGNIZED WELD TYPE. BUTT-WELD ASSUMED.
*** LAST NODE PROCESSED: 460 F
FLA  460 F        NS   NS                                                       
          *** WARNING: UNRECOGNIZED WELD TYPE. BUTT-WELD ASSUMED.
*** LAST NODE PROCESSED: 675  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 705  
RED  705               -50.800   609.600     0.000     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.
*** LAST NODE PROCESSED: 705  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 705  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 775  
RED  775                 0.000   280.416   707.136     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.
*** LAST NODE PROCESSED: 775  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 775  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 850  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 870  
RED  870                 0.000   300.000     0.000     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.
*** LAST NODE PROCESSED: 870  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 870  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 900  
RED  900               -50.800   609.600     0.000     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.
*** LAST NODE PROCESSED: 900  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 900  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 950  
RED  950                 0.000   280.417   707.136     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.
*** LAST NODE PROCESSED: 950  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 950  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 970  
RED  970                 0.000   446.640  1113.780     0.000                    
          *** WARNING: CONE ANGLE DOES NOT APPLY TO THIS CODE.
*** LAST NODE PROCESSED: 970  
    *CS                   0.06                                                  
          *** WARNING: UNKNOWN MATERIAL. SETTING MATERIAL TO CS.
*** LAST NODE PROCESSED: 10   
INCL 95           W            2540.0000 1000.0000    0.0000    0.0000    0.0000
          *** NOTE: SUPPORT NAMES GENERATED BY TRANSLATOR


      DATABASE ARRAY SIZE IS  73209.  MAXIMUM ALLOWABLE IS   10000000



 ********** NUMBER OF ERRORS:   4
 ********** NUMBER OF WARNINGS:  33


