          * * * *  APOUT MESSAGE FILE  * * * * 


 WARNING: MISSING FORCE SPECTRUM DATA FILE -         
 FORCE SPECTRUM CASE 1 WAS NOT EXPORTED TO NTL FILE
 WARNING: MISSING FORCE SPECTRUM DATA FILE -         
 FORCE SPECTRUM CASE 2 WAS NOT EXPORTED TO NTL FILE
 WARNING: MISSING FORCE SPECTRUM DATA FILE -         
 FORCE SPECTRUM CASE 3 WAS NOT EXPORTED TO NTL FILE



 *** BATCH FILE CREATION COMPLETE ***

 *** NUMBER OF ERRORS =  0
 *** NUMBER OF WARNINGS =  3


